name: 'Limit changes'
description: 'Limit number of changed lines in the pull request'
inputs:
  limit:
    description: Limit of changes
    required: true
  extension:
    description: >
      File extensions that you want to count changes. 
      Do not include "." before extensions.
      Use regular expressions if you want to specify multiple extensions.
      (example) kt|yml|gradle
    required: true
  exclude_dir:
    description: >
      Directories where you don't want to count changes.
      Do not add "/" at the end of directory name.
    required: false
    default: ""
  token:
    description: >
      GitHub token to add comment by this actions\
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}

    - name: Save Base ref
      shell: bash
      run: echo BASE=`git rev-parse HEAD` >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Set env
      shell: bash
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        echo "EXT=${{ inputs.extension }}" >> $GITHUB_ENV
        echo "EXCLUDE=${{ inputs.exclude_dir }}" >> $GITHUB_ENV
        echo "LIMIT=${{ inputs.limit }}" >> $GITHUB_ENV
        echo "URL=${{ github.event.pull_request.comments_url }}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV

    - name: Count number of changed lines
      id: count_changes
      shell: bash
      run: count_diff.sh

    - name: Add comment
      shell: bash
      run: |
        echo "::group::Add comment"
        TEXT=":sparkles:OK:sparkles:"
        curl \
          --silent \
          -X POST \
          $URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          --data "{ \"body\": \"$TEXT\"}"
        echo "::endgroup::"

    - name: Add error comment if exceeds limit
      if: failure() && steps.count_changes.outcome == 'failure'
      shell: bash
      run: |
        echo "::group::Add error comment"
        TITLE="**The number of changed lines exceeds the limit.**"
        INFO=":hammer_and_wrench:LIMIT: $LIMIT, :fire:Changed: $CHANGED"
        curl \
          --silent \
          -X POST \
          $URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          --data "{ \"body\": \"$TITLE\n$INFO\"}"
        echo "::endgroup::"