name: On pull request
on:
  pull_request:

jobs:
  limit-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/limit
        with:
          limit: 100
          extension: kt|java
          exclude_dir: app/src/test
          token: ${{ secrets.GITHUB_TOKEN }}